use ratatui::style::Color;
use stakai::Model;
use stakpak_api::models::ListRuleBook;
use stakpak_shared::models::{
    integrations::openai::{ToolCall, ToolCallResult, ToolCallResultProgress, ToolCallStreamInfo},
    llm::LLMTokenUsage,
};
use uuid::Uuid;

use crate::app::{ExistingPlanPrompt, LoadingOperation, SessionInfo};
use crate::services::banner::BannerStyle;
use crate::services::board_tasks::FetchTasksResult;

#[derive(Debug)]
pub enum InputEvent {
    AssistantMessage(String),
    AddUserMessage(String),
    StreamAssistantMessage(Uuid, String),
    RunToolCall(ToolCall),
    ToolResult(ToolCallResult),
    StreamToolResult(ToolCallResultProgress),
    /// Progress update while tool calls are being streamed/generated by the LLM
    StreamToolCallProgress(Vec<ToolCallStreamInfo>),
    StartLoadingOperation(LoadingOperation),
    EndLoadingOperation(LoadingOperation),
    InputChanged(char),
    ShellMode,
    RunShellCommand(String),
    /// Spawn the user's shell and then execute a command in it (for interactive stall recovery)
    RunShellWithCommand(String),
    GetStatus(String),
    BillingInfoLoaded(stakpak_shared::models::billing::BillingResponse),
    Error(String),
    SetSessions(Vec<SessionInfo>),
    SetBannerMessage(String, BannerStyle),
    InputBackspace,
    InputChangedNewline,
    InputSubmitted,
    InputSubmittedWith(String),
    InputSubmittedWithColor(String, Color),
    MessageToolCalls(Vec<ToolCall>),
    ScrollUp,
    ScrollDown,
    PageUp,
    PageDown,
    DropdownUp,
    DropdownDown,
    Up,
    Down,
    Quit,
    HandleEsc,
    HandleReject(Option<String>, bool, Option<Color>),
    CursorLeft,
    CursorRight,
    ToggleCursorVisible,
    Resized(u16, u16),
    ShowConfirmationDialog(ToolCall),
    HasUserMessage,
    Tab,
    ToggleApprovalStatus,
    ShellOutput(String),
    ShellError(String),
    ShellWaitingForInput,
    ShellCompleted(i32),
    ShellClear,
    ShellKill,
    HandlePaste(String),
    /// Ctrl+V clipboard image paste (non-text, via system clipboard).
    HandleClipboardImagePaste,
    InputDelete,
    InputDeleteWord,
    InputCursorStart,
    InputCursorEnd,
    InputCursorPrevWord,
    InputCursorNextWord,
    ToggleAutoApprove,
    AutoApproveCurrentTool,
    ToggleDialogFocus,
    RetryLastToolCall,
    /// Interactive stall detected - automatically switch to shell mode and fire the command
    InteractiveStallDetected(String),
    AttemptQuit,
    ToggleCollapsedMessages,
    ShowFileChangesPopup,
    // Auto-approve popup events
    ShowAutoApprovePopup,
    FileChangesRevertFile,
    FileChangesRevertAll,
    FileChangesOpenEditor,
    EmergencyClearTerminal,
    ToggleMouseCapture,
    OpenFileInEditor,
    // Approval popup events
    ApprovalPopupNextTab,
    ApprovalPopupPrevTab,
    ApprovalPopupToggleApproval,
    ApprovalPopupSubmit,
    ApprovalPopupEscape,
    // Approval bar events (inline approval)
    ApprovalBarApproveAll,
    ApprovalBarRejectAll,
    ApprovalBarSelectAction(usize),
    ApprovalBarApproveSelected,
    ApprovalBarRejectSelected,
    ApprovalBarNextAction,
    ApprovalBarPrevAction,
    ApprovalBarCollapse,
    // Profile switcher events
    ShowProfileSwitcher,
    ProfilesLoaded(Vec<String>, String),
    ProfileSwitchRequested(String),
    ProfileSwitchProgress(String),
    ProfileSwitchComplete(String),
    ProfileSwitchFailed(String),
    // Command palette events
    ShowCommandPalette,
    CommandPaletteSearchInputChanged(char),
    CommandPaletteSearchBackspace,
    ProfileSwitcherSelect,
    ProfileSwitcherCancel,
    // Shortcuts popup events
    ShowShortcuts,
    ShortcutsCancel,

    // Rulebook switcher events
    ShowRulebookSwitcher,
    RulebooksLoaded(Vec<ListRuleBook>),
    CurrentRulebooksLoaded(Vec<String>),
    RulebookSwitcherSelect,
    RulebookSwitcherToggle,
    RulebookSwitcherCancel,
    RulebookSwitcherConfirm,
    RulebookSwitcherSelectAll,
    RulebookSwitcherDeselectAll,
    RulebookSearchInputChanged(char),
    RulebookSearchBackspace,
    HandleCtrlS,
    ToggleMoreShortcuts,
    // Usage tracking events
    StreamUsage(LLMTokenUsage),
    RequestTotalUsage,
    TotalUsage(LLMTokenUsage),

    // Model events
    StreamModel(Model),

    // Model switcher events
    ShowModelSwitcher,
    AvailableModelsLoaded(Vec<Model>),
    ModelSwitcherSelect,
    ModelSwitcherCancel,
    ModelSwitcherSearchInputChanged(char),
    ModelSwitcherSearchBackspace,
    /// Update recent models list (sent after model switch is saved)
    RecentModelsUpdated(Vec<String>),

    // Side panel events
    ToggleSidePanel,
    SidePanelNextSection,
    SidePanelToggleSection,

    // Mouse events
    MouseClick(u16, u16),
    MouseDragStart(u16, u16),
    MouseDrag(u16, u16),
    MouseDragEnd(u16, u16),
    MouseMove(u16, u16),

    // Board tasks events
    RefreshBoardTasks,
    BoardTasksLoaded(FetchTasksResult),
    BoardTasksError(String),

    // Plan mode events
    /// Plan mode toggled on/off (sent from backend to TUI to sync state)
    PlanModeChanged(bool),
    /// Existing plan found at startup — show the modal with metadata and stashed prompt
    ExistingPlanFound(ExistingPlanPrompt),
    /// Toggle plan review overlay (Ctrl+P in plan mode)
    TogglePlanReview,
    /// Close plan review overlay
    PlanReviewClose,
    /// Move cursor up in plan review
    PlanReviewCursorUp,
    /// Move cursor down in plan review
    PlanReviewCursorDown,
    /// Open comment modal for current line
    PlanReviewComment,
    /// Approve the plan
    PlanReviewApprove,
    /// Submit feedback (unresolved comments)
    PlanReviewFeedback,
    /// Jump to next commented line
    PlanReviewNextComment,
    /// Jump to previous commented line
    PlanReviewPrevComment,
    /// Toggle resolve on selected comment
    PlanReviewResolve,
    /// Scroll plan review up by a page
    PlanReviewPageUp,
    /// Scroll plan review down by a page
    PlanReviewPageDown,

    // Ask User popup events
    ShowAskUserPopup(
        ToolCall,
        Vec<stakpak_shared::models::integrations::openai::AskUserQuestion>,
    ),
    AskUserNextTab,
    AskUserPrevTab,
    AskUserNextOption,
    AskUserPrevOption,
    AskUserSelectOption,
    AskUserConfirmQuestion,
    AskUserCustomInputChanged(char),
    AskUserCustomInputBackspace,
    AskUserCustomInputDelete,
    AskUserSubmit,
    AskUserCancel,

    // Clipboard events
    CopySessionId,

    // Session events
    SetSessionId(String),

    // Approval settings persistence modal events
    ShowApprovalSettingsPersistenceModal,
    ApprovalSettingsPersistenceNavigate(i32),
    ApprovalSettingsPersistenceConfirm,
    ApprovalSettingsPersistenceCancel,
}

impl InputEvent {
    /// Returns true for events sent by the backend (stream, CLI) that must never be
    /// consumed by popup interceptors. These events drive the message pipeline and
    /// blocking them causes the TUI to get stuck in a loading state.
    ///
    /// **Important:** When adding new `InputEvent` variants that originate from the
    /// backend (mode_interactive, stream, helpers, etc.), add them here too —
    /// otherwise they'll be silently dropped when any popup is open.
    pub fn is_backend_event(&self) -> bool {
        matches!(
            self,
            InputEvent::StreamAssistantMessage(_, _)
                | InputEvent::AssistantMessage(_)
                | InputEvent::StartLoadingOperation(_)
                | InputEvent::EndLoadingOperation(_)
                | InputEvent::StreamUsage(_)
                | InputEvent::StreamModel(_)
                | InputEvent::StreamToolCallProgress(_)
                | InputEvent::StreamToolResult(_)
                | InputEvent::HasUserMessage
                | InputEvent::Error(_)
                | InputEvent::RunToolCall(_)
                | InputEvent::ToolResult(_)
                | InputEvent::MessageToolCalls(_)
                | InputEvent::ShowConfirmationDialog(_)
                | InputEvent::AddUserMessage(_)
                | InputEvent::PlanModeChanged(_)
                | InputEvent::BoardTasksLoaded(_)
                | InputEvent::BoardTasksError(_)
                | InputEvent::ShowAskUserPopup(_, _)
                | InputEvent::ExistingPlanFound(_)
                | InputEvent::SetSessions(_)
                | InputEvent::SetBannerMessage(_, _)
                | InputEvent::GetStatus(_)
                | InputEvent::BillingInfoLoaded(_)
                | InputEvent::TotalUsage(_)
                | InputEvent::ProfileSwitchProgress(_)
                | InputEvent::ProfileSwitchComplete(_)
                | InputEvent::ProfileSwitchFailed(_)
                | InputEvent::ProfilesLoaded(_, _)
                | InputEvent::AvailableModelsLoaded(_)
                | InputEvent::RecentModelsUpdated(_)
                | InputEvent::RulebooksLoaded(_)
                | InputEvent::CurrentRulebooksLoaded(_)
        )
    }
}

#[derive(Debug)]
pub enum OutputEvent {
    /// User message with optional tool call results, image parts, and revert index
    /// The revert index (if Some) indicates that messages should be truncated to that user message index
    UserMessage(
        String,
        Option<Vec<ToolCallResult>>,
        Vec<stakpak_shared::models::integrations::openai::ContentPart>,
        Option<usize>, // revert_to_user_message_index
    ),
    AcceptTool(ToolCall),
    RejectTool(ToolCall, bool),
    ListSessions,
    SwitchToSession(String),
    NewSession,
    SendToolResult(ToolCallResult, bool, Vec<ToolCall>),
    ResumeSession,
    RequestProfileSwitch(String),
    RequestRulebookUpdate(Vec<String>),
    RequestCurrentRulebooks,
    RequestTotalUsage,
    RequestAvailableModels,
    SwitchToModel(Model),
    /// Save recent models list to config (used when initial model is added)
    SaveRecentModels(Vec<String>),
    /// Plan mode activated via /plan command. Contains optional inline prompt.
    PlanModeActivated(Option<String>),
    /// Feedback on the plan — formatted unresolved comments injected as user message.
    PlanFeedback(String),
    /// Plan approved — transition to Executing phase.
    PlanApproved,
    /// A slash command was invoked.
    CommandCalled(String),
    /// Response from ask_user popup with the tool call and result
    AskUserResponse(ToolCallResult),
    /// Save auto-approve settings to the profile config (tool names set to Auto)
    SaveAutoApproveToProfile(Vec<String>),
}
